felinederma/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('sitederma.urls', namespace="sitederma")),
]

sitederma/urls.py
from django.conf.urls import url
from . import views
from .forms import LoginForm, Kucing
from django.contrib.auth.views import login

urlpatterns = [
    #/home_utama/
    url(r'^$', views.home_utama, name='home_utama'),
    url(r'^kontak/$', views.kontak_view, name='kontak'),
    url(r'^bantuan/$', views.help_view, name='help'),
    url(r'^masuk/$', login, name='login', kwargs={"authentication_form" : LoginForm}),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^info_penyakit/$', views.infopenyakit_view, name='infopenyakit'),
    url(r'^info_klinik/$', views.infoklinik_view, name='infoklinik'),
    url(r'^daftar/$', views.signup_view, name='signup'),
    url(r'^daftar/sukses/$', views.signupsucces_view, name='signupsucces'),
    url(r'^akun/konfirmasi/(?P<activation_key>\w+)/$', views.account_confirmation_view, name='account_confirmation'),
    url(r'^akun/konfirm/$', views.account_confirmed_view, name='account_confirmed'),
    url(r'^akun/kadaluarsa/$', views.account_expired_view, name='account_expired'),
    url(r'^profil/$', views.profil_view, name='profil'),
    # halaman konsul
    url(r'^input_kucing/$', views.inputkucing_view, name='inputkucing'),
    url(r'^konsultasi/$', views.konsultasi_view, name='konsultasi'),
    url(r'^riwayat/$', views.riwayat_view, name='riwayat'),
    url(r'^hasil/$', views.hasil_view, name='hasil'),

]

sitederma/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
import datetime
from django.core.validators import MinValueValidator

class UserActivationKey(models.Model):
    user = models.OneToOneField(User)
    activation_key = models.CharField(max_length=40, blank=True)
    key_expires = models.DateTimeField(default=datetime.date.today())
    def __str__(self):
        return self.user.username

class Kucing(models.Model):
    GENDER_KUCING_CHOICES = (
    ('betina', 'Betina'),
    ('jantan', 'Jantan'),
    )

    nama_kucing = models.CharField(max_length=30)
    umur_kucing = models.PositiveIntegerField(validators=[MinValueValidator(1)], null=True)
    gender_kucing = models.CharField(max_length=10, choices=GENDER_KUCING_CHOICES)
    username = models.ForeignKey(User, null=True)
    def __str__(self):
        return self.nama_kucing

class InfoKlinik(models.Model):
    nama_klinik = models.CharField(max_length=50)
    wilayah = models.CharField(max_length=50)
    alamat = models.TextField()
    no_telp = models.CharField(max_length=15)

    def __str__(self):
        return self.nama_klinik

class InfoPenyakit(models.Model):
    kode_penyakit = models.CharField(max_length=5, null=True)
    nama_penyakit = models.CharField(max_length=30)
    info_umum = models.TextField()
    penyebab = models.TextField()
    gejala = models.TextField()
    pengobatan = models.TextField()
    pencegahan = models.TextField()
    peringatan = models.TextField(blank=True)

    def __str__(self):
        return self.kode_penyakit

class ListGejala(models.Model):
    kode_gejala = models.CharField(max_length=5)
    nama_gejala = models.CharField(max_length=100)
    def __str__(self):
        return self.kode_gejala

class ListTanya(models.Model):
    kode_tanya = models.CharField(max_length=5)
    kode_gejala = models.ForeignKey(ListGejala, related_name = 'tanya_gejala', null=True)
    no_tanya = models.CharField(max_length=2, null=True)
    daftar_tanya = models.CharField(max_length=150)
    def __str__(self):
        return self.daftar_tanya

class Konsultasi(models.Model):
    kodecf = models.CharField(max_length=3)
    kode_penyakit = models.ForeignKey(InfoPenyakit, null=True)
    kode_gejala = models.ForeignKey(ListGejala)
    cfp = models.FloatField()
    def __str__(self):
        return self.kodecf

class Jawaban(models.Model):
    kodejawab = models.CharField(max_length=3)
    jawab = models.CharField(max_length=10)
    bobotjawab = models.FloatField()
    def __str__(self):
        return self.jawab

class Riwayat(models.Model):
    nama_kucing = models.ForeignKey(Kucing, related_name = 'request_nama_kucing')
    username = models.ForeignKey(User, related_name = 'request_username')
    hasil_diagnosa = models.FloatField(max_length=30, null=True)
    tanggal_diagnosa = models.DateTimeField(blank=True, null=True)
    def __str__(self):
        return self.nama_kucing

sitederma/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Kucing, Riwayat


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='username', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'username'}))
    password = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'password'}))

class SignupForm(UserCreationForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'username'}))
    first_name = forms.CharField(label='First Name', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'firtsname'}))
    last_name = forms.CharField(label='Last Name', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'lastname'}))
    email = forms.EmailField(label='Email', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'email'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'password'}))
    password2 = forms.CharField(label='Re-Password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 're-password'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email yang anda masukan sudah terdaftar")
        return email

class KucingForm(forms.ModelForm):
    nama_kucing = forms.CharField(label='Nama Kucing', widget=forms.TextInput)

    class Meta:
        model = Kucing
        fields = ('nama_kucing', 'umur_kucing', 'gender_kucing')

class RiwayatForm(forms.ModelForm):
    class Meta:
        model = Riwayat
        fields = ('nama_kucing',)

sitederma/views.py
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .forms import SignupForm, KucingForm, RiwayatForm
import hashlib, datetime, random
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.models import User
from .models import UserActivationKey, ListTanya, InfoPenyakit, Jawaban, ListGejala, Konsultasi, InfoKlinik, Kucing
from django.utils import timezone
from collections import defaultdict
import operator

def home_utama(request):
    return render(request, "sitederma/home_utama.html")

def kontak_view(request):
    return render(request, "sitederma/kontak.html")

def help_view(request):
    return render(request, "sitederma/bantuan.html")

def infopenyakit_view(request):
    info_penyakit = InfoPenyakit.objects.all()
    gejala = ListGejala.objects.all()
    kode = Konsultasi.objects.all()
    context = {}
    context ['info_penyakit'] = info_penyakit
    context ['gejala'] = gejala
    context ['kode'] = kode
    return render(request, "sitederma/infopenyakit.html", context)

def infoklinik_view(request):
    info_klinik = InfoKlinik.objects.all()
    context = {}
    context ['info_klinik'] = info_klinik
    return render(request, "sitederma/infoklinik.html", context)

def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            username = form.cleaned_data['username']
            email = form.cleaned_data['email']

            activation_key = hashlib.sha224((email).encode('utf-16be')).hexdigest()
            key_expires = datetime.datetime.today() + datetime.timedelta(2)

            user=User.objects.get(username=username)
            user_activation_key = UserActivationKey(user=user, activation_key=activation_key, key_expires=key_expires)
            user_activation_key.save()

            host=request.META['HTTP_HOST']
            email_subject = 'Konfirmasi Akun'
            email_body = "Halo {}, Terima kasih telah melakukan pendaftaran di Sitederma. Selamat datang di aplikasi sitederma. Untuk melanjutkan silahkan melakukan aktivasi akun anda dengan klik pada link di bawah kurang daei 48 jam.\
             http://{}/akun/konfirmasi/{}".format(username, host, activation_key)

            from_email = settings.EMAIL_HOST_USER
            to_email = [user.email, settings.EMAIL_HOST_USER]

            send_mail(email_subject, email_body, from_email, to_email, fail_silently=False)

            return HttpResponseRedirect('/daftar/sukses')

    else:
        form = SignupForm()

    return render(request, 'sitederma/signup.html', {'form': form})


def signupsucces_view(request):
    return render(request, "sitederma/signupsucces.html")

def account_confirmation_view(request, activation_key):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/home_utama.html')

    user_activation = get_object_or_404(UserActivationKey, activation_key=activation_key)
    if user_activation.key_expires < timezone.now():
        return render_to_response('/account_expired.html')
    user = user_activation.user
    user.is_active = True
    user.save()
    return render_to_response('sitederma/account_confirmed.html')

def account_confirmed_view():
    return render(request, "sitederma/account_confirmed.html")

def account_expired_view():
    return render(request, "sitederma/account_expired.html")

def profil_view(request):
    return render(request, "sitederma/profil.html")


def inputkucing_view(request):
    infokucing = Kucing.objects.all()
    context = {}
    context ['infokucing'] = infokucing

    if request.method == 'POST':
        form = KucingForm(request.POST)
        if form.is_valid():
            kucing = form.save(commit=False)
            kucing.username = request.user
            kucing.save()

            return HttpResponseRedirect('/input_kucing/')
    else:
        form = KucingForm()

    return render(request, 'sitederma/inputkucing.html', {'form': form})

def konsultasi_view(request):
    diagnosa = None
    list_tanya = ListTanya.objects.all()
    list_pilihan = Jawaban.objects.all()
    gejala = ListGejala.objects.all()
    context = {}
    context ['list_tanya'] = list_tanya
    context ['list_pilihan'] = list_pilihan

    if request.method=='POST':
        formriwayat = RiwayatForm(request.POST)
        d = defaultdict(float)
        d = {}
        cfgp1_={}
        percentdisease = {}
        counter = 1

        for cfuser in gejala:
            d['cfug_%02d' % counter] = float(request.POST.get(cfuser.kode_gejala))
            counter += 1
        for key, value in sorted(d.items()):
            print (key, value)
        penyakit = InfoPenyakit.objects.all()
        gej_pen = Konsultasi.objects.all()

        for pen in penyakit:
            cfglama = None
            cfgbaru = None
            cfgkombinasi = None
            for gejala_penyakit in gej_pen:
                if gejala_penyakit.kode_penyakit.kode_penyakit == pen.kode_penyakit:
                    print('ya')
                    urut = gejala_penyakit.kode_gejala.kode_gejala[1:]
                    print(urut)
                    cfgp1_['cfg{0}'.format(urut)] = d['cfug_{}'.format(urut)] * gejala_penyakit.cfp
                    if not cfglama:
                        cfglama = cfgp1_['cfg{0}'.format(urut)]
                    else :
                        cfgbaru = cfgp1_['cfg{0}'.format(urut)]
                        cfgkombinasi = cfglama+(cfgbaru*(1-cfglama))
                        cfglama = cfgkombinasi
                    percentdisease['pdisease{0}'.format(pen.kode_penyakit)] = cfgkombinasi
                    print(percentdisease)
        context['percentdisease_1'] = percentdisease['pdisease{0}'.format('P1')]
        context['percentdisease_2'] = percentdisease['pdisease{0}'.format('P2')]
        context['percentdisease_3'] = percentdisease['pdisease{0}'.format('P3')]
        context['percentdisease_4'] = percentdisease['pdisease{0}'.format('P4')]
        context['percentdisease_5'] = percentdisease['pdisease{0}'.format('P5')]
        context['percentdisease_6'] = percentdisease['pdisease{0}'.format('P6')]
        targetdisease = max(percentdisease, key=percentdisease.get)
        context['targetdisease'] = targetdisease
        if targetdisease == "diseaseP1":
            diagnosa ='Ear Mites'
        elif targetdisease == "diseaseP2":
            diagnosa = 'Flea'
        elif targetdisease == "diseaseP3":
            diagnosa = 'Lice'
        elif targetdisease == "diseaseP4":
            diagnosa = 'Pyoderma'
        elif targetdisease == "diseaseP5":
            diagnosa = 'Ringworm'
        elif targetdisease == "diseaseP6":
            diagnosa = 'Scabies'
        request.session['percentdisease'] = {
                                        'percentdisease_1': context['percentdisease_1'],
                                        'percentdisease_2': context['percentdisease_2'],
                                        'percentdisease_3': context['percentdisease_3'],
                                        'percentdisease_4': context['percentdisease_4'],
                                        'percentdisease_5': context['percentdisease_5'],
                                        'percentdisease_6': context['percentdisease_6'],
                                        'targetdisease': context['targetdisease'],
                                        }
        if formriwayat.is_valid():
            kucing = formriwayat.save(commit=False)
            kucing.username = request.user
            kucing.tanggal_diagnosa = timezone.now()
            kucing.hasil_diagnosa = diagnosa
            kucing.save()
            return HttpResponseRedirect(reverse('sitederma:hasil'))
    else:
        formriwayat = RiwayatForm()
    context['formriwayat']=formriwayat
    return render(request, "sitederma/mulai_konsul.html",  context)

def hasil_view(request):
    context = request.session.get('percentdisease')

    return render(request, "sitederma/halaman_hasil.html", context)

def riwayat_view(request):
    return render(request, "sitederma/riwayat.html")

@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

sitederma/templates/sitederma/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
  <link rel="shortcut icon" href="{% static 'image/Logo1.png'%}"/>
  <title> Feline Dermatology</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="{% static 'bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'css/sitederma.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'sitederma:home_utama' %}">FiDerma</a>
      </div>
      {% if user.is_authenticated %}
      <ul class="nav navbar-nav">
        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'sitederma:profil' %}"><span class="glyphicon glyphicon-user "></span> {{request.user.username}} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'sitederma:profil' %}">Profil Pengguna</a></li>
            <li><a href="{% url 'sitederma:inputkucing' %}">Profil Kucing</a></li>
          </ul>
        </li>
        <li><a href="{% url 'sitederma:home_utama' %}">Beranda</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Konsultasi<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'sitederma:konsultasi' %}">Mulai Konsultasi</a></li>
              <li><a href="{% url 'sitederma:riwayat' %}">Riwayat Konsultasi</a></li>
            </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Info<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'sitederma:infopenyakit' %}">Info Penyakit</a></li>
              <li><a href="{% url 'sitederma:infoklinik' %}">Info Klinik</a></li>
            </ul>
        </li>
        <li><a href="{% url 'sitederma:kontak' %}">Kontak</a></li>
        <li><a href="{% url 'sitederma:help'%}">Bantuan</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'sitederma:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Keluar</a></li>
      </ul>
      {% else %}
      <ul class="nav navbar-nav">
        <li><a href="{% url 'sitederma:home_utama' %}">Beranda</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Info<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'sitederma:infopenyakit' %}">Info Penyakit</a></li>
              <li><a href="{% url 'sitederma:infoklinik' %}">Info Klinik</a></li>
            </ul>
        </li>
        <li><a href="{% url 'sitederma:kontak' %}">Kontak</a></li>
        <li><a href="{% url 'sitederma:help' %}">Bantuan</a></li>
      </ul>

      {% endif %}
    </div>
  </nav>

      {% block content %}

      {% endblock %}

      <footer class="footer">
        <div class="container">
          <div class="row vitra-footer text-center">
            <p>&copy; FiDerma 2017 Design by Vitra Yolanda Aprilia</p>
          </div>
        </div>
      </footer>

      <script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>
      <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    </body>

</html>

sitederma/templates/sitederma/home_utama.html
{% extends 'sitederma/base.html' %}

{% load static %}

{% block content %}
{% if user.is_authenticated %}

<!-- halaman setelah melakukan login -->
<div class="container-fluid vitra-background-beranda">
  <div class="row">
    <div id="vitra-background-green">
      <div class="col-md-2"></div>
      <div class="col-md-8 text-center">
        <div style="margin: 50px 0px;">
        <img src="{% static 'image/logofinish.png'%}" class="img-thumbnail" width="400" height="400"/>
          <p class="vitra-tagline">"your feline dermatology bestfriend"</p>
        </div>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>

  <div class="row">
    <div id="vitra-background-deep">
    <div class="col-md-2"></div>
    <div class="col-md-8 text-center">
      <div style="margin: 50px 0px;">
        <p class="vitra-tagline">Penyakit Kulit pada Kucing</p>
        <div id="myCarousel" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
    <li data-target="#myCarousel" data-slide-to="5"></li>
    <li data-target="#myCarousel" data-slide-to="6"></li>
    <li data-target="#myCarousel" data-slide-to="7"></li>
    <li data-target="#myCarousel" data-slide-to="8"></li>
    <li data-target="#myCarousel" data-slide-to="9"></li>
    <li data-target="#myCarousel" data-slide-to="10"></li>
    <li data-target="#myCarousel" data-slide-to="11"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <!-- untuk tampilan slide ear mites   -->
    <div class="item active">
      <img src="{% static 'image/logofinish.png'%}" class="img-thumbnail" width="200" height="200"/>
    </div>
    <div class="item">
      <p class="vitra-tentang">FiDerma adalah aplikasi berbasis website yang dapat membantu kamu untuk mendiagnosis penyakit kulit yang sedang diderita oleh kucing kesayanganmu.
        Aplikasi ini dapat membantumu untuk menangani secara dini penyakit kulit pada kucing sebelum diperiksakan ke dokter hewan</p>
    </div>

    <!-- untuk tampilan slide flea -->
    <div class="item">
      <img src="{% static 'image/logofinish.png'%}" class="img-thumbnail" width="200" height="200"/>
    </div>
    <div class="item">
      <p class="vitra-tentang">FiDerma adalah aplikasi berbasis website yang dapat membantu kamu untuk mendiagnosis penyakit kulit yang sedang diderita oleh kucing kesayanganmu.
        Aplikasi ini dapat membantumu untuk menangani secara dini penyakit kulit pada kucing sebelum diperiksakan ke dokter hewan</p>
    </div>

    <!-- untuk tampilan slide lice -->
    <div class="item">
      <img src="{% static 'image/logofinish.png'%}" class="img-thumbnail" width="200" height="200"/>
    </div>
    <div class="item">
      <p class="vitra-tentang">FiDerma adalah aplikasi berbasis website yang dapat membantu kamu untuk mendiagnosis penyakit kulit yang sedang diderita oleh kucing kesayanganmu.
        Aplikasi ini dapat membantumu untuk menangani secara dini penyakit kulit pada kucing sebelum diperiksakan ke dokter hewan</p>
    </div>

    <!-- untuk tampilan slide pyoderma -->
    <div class="item">
      <img src="{% static 'image/logofinish.png'%}" class="img-thumbnail" width="200" height="200"/>
    </div>
    <div class="item">
      <p class="vitra-tentang">FiDerma adalah aplikasi berbasis website yang dapat membantu kamu untuk mendiagnosis penyakit kulit yang sedang diderita oleh kucing kesayanganmu.
        Aplikasi ini dapat membantumu untuk menangani secara dini penyakit kulit pada kucing sebelum diperiksakan ke dokter hewan</p>
    </div>

    <!-- untuk tampilan slide ringworm -->
    <div class="item">
      <img src="{% static 'image/logofinish.png'%}" class="img-thumbnail" width="200" height="200"/>
    </div>
    <div class="item">
      <p class="vitra-tentang">FiDerma adalah aplikasi berbasis website yang dapat membantu kamu untuk mendiagnosis penyakit kulit yang sedang diderita oleh kucing kesayanganmu.
        Aplikasi ini dapat membantumu untuk menangani secara dini penyakit kulit pada kucing sebelum diperiksakan ke dokter hewan</p>
    </div>

    <!-- untuk tampilan slide scabies -->
    <div class="item">
      <img src="{% static 'image/logofinish.png'%}" class="img-thumbnail" width="200" height="200"/>
    </div>
    <div class="item">
      <p class="vitra-tentang">FiDerma adalah aplikasi berbasis website yang dapat membantu kamu untuk mendiagnosis penyakit kulit yang sedang diderita oleh kucing kesayanganmu.
        Aplikasi ini dapat membantumu untuk menangani secara dini penyakit kulit pada kucing sebelum diperiksakan ke dokter hewan</p>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
      </div>
    </div>
  </div>

<!-- halaman jika belum login -->
  {% else %}
  <div class="container-fluid vitra-background-beranda">
  <div class="row">
    <div id="vitra-background-green">
      <div class="col-md-2"></div>
      <div class="col-md-8 text-center">
        <div style="margin: 50px 0px;">
        <img src="{% static 'image/logofinish.png'%}" class="img-thumbnail" width="400" height="400"/>
          <p class="vitra-tagline">"your feline dermatology bestfriend"</p>
        </div>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>

  <div class="row">
    <div id="vitra-background-deep">
    <div class="col-md-2"></div>
    <div class="col-md-8 text-center">
      <div style="margin: 50px 0px;">
        <p class="vitra-tagline">APA ITU FIDERMA?</p>
        <div id="myCarousel" class="carousel slide text-center" data-ride="carousel">

        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <p class="vitra-tentang">FiDerma adalah aplikasi berbasis website yang dapat membantu kamu untuk mendiagnosis penyakit kulit yang sedang diderita oleh kucing kesayanganmu.
              Aplikasi ini dapat membantumu untuk menangani secara dini penyakit kulit pada kucing sebelum diperiksakan ke dokter hewan</p>
          </div>
          <div class="item">
            <p class="vitra-tentang">FiDerma berasal dari kata "Feline" yang artinya adalah kucing dan "Dermatology" adalah salah satu cabang ilmu kedokteran yang mempelajari tentang kulit</p>
          </div>
          <div class="item">
              <p class="vitra-tentang">Untuk mempelajari cara menggunakan aplikasi, klik pada menu Bantuan</p>
          </div>
        </div>

        <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
  </div>
  </div>
</div>
</div>

  <div class="row">
    <div id="vitra-background-grey">
    <div class="col-md-2"></div>
    <div class="col-md-8 text-center">
      <div style="margin: 50px 0px;">
    <p class="vitra-daftar">ingin melakukan konsultasi? silahkan masuk atau daftar terlebih dahulu</p>
      <a href="{% url 'sitederma:login' %}"><button class="btn btn-lg">Masuk</button></a>
      <a href="{% url 'sitederma:signup' %}"><button class="btn btn-lg">Daftar</button></a>
  </div>
  </div>
</div>
</div>
</div>
  {% endif %}
</div>
{% endblock %}